language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug   FORCE_BUILD=off
  - BUILD_TYPE=Release FORCE_BUILD=off
  - BUILD_TYPE=Debug   FORCE_BUILD=on
  - BUILD_TYPE=Release FORCE_BUILD=on

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install sqlite3 libsqlite3-dev

install:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on -DBUILD_TESTS_WITH_EIGEN=on -DFORCE_DEPENDENCIES_BUILD=$FORCE_BUILD ..
  - make
  - cd ..

script:
  - cd build
  - ctest -V