language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - sudo apt-get install libeigen3-dev
  - sudo apt-get install gsl-bin libgsl0-dbg libgsl0-dev libgsl0ldbl
  - curl -OL http://ftp.gnu.org/gnu/automake/automake-1.14.1.tar.gz
  - tar -xzf automake-1.14.1.tar.gz
  - cd automake-1.14.1
  - ./configure 
  - make 
  - sudo make install
  - cd ..
  - git clone https://github.com/kartikkumar/sgp4deorbit sgp4
  - cd sgp4
  - automake --add-missing
  - ./configure
  - make
  - cd ..
  - git clone https://www.github.com/kartikkumar/sml
  - cd sml 
  - git submodule init
  - git submodule update
  - cmake -HSML -Bbuild
  - cd build
  - make
  - cd ..
  - cd ..
  - git clone https://www.github.com/kartikkumar/sam
  - cd sam
  - git submodule init
  - git submodule update
  - cmake -HSAM -Bbuild
  - cd build
  - make
  - cd ..
  - cd ..  
  - git clone https://www.github.com/kartikkumar/atom
  - cd atom
  - git submodule init
  - git submodule update
  - cmake -HAtom -Bbuild
  - cd build
  - make
  - cd ..
  - cd ..    

install:
  - cmake -HD2D -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on
  - cd build
  - make
  - cd ..

script:
  - cd build
  - ctest -V